### ISSUE TITLE
Allow Statistics to render from mock data

### ISSUE THREAD

**Issue by MayKikuchi** [Dara2004/Goi#55]

**Comment by ZhiHanL** [comment]
Ah just noticed that you're working on this... Is it the same as this issue? #49 
Just want to make sure that we're not working on the same thing

**Comment by MayKikuchi** [comment]
oh shoot! I think it is! sorry, didn't realize it already had an issue open for it!

**Comment by ZhiHanL** [comment]
Ah okay, dang it. I'm done the stats table if you want to use it. Think it looks a bit nice than what you have currently (just followed a template online)

**Comment by ZhiHanL** [comment]
Just check out my branch "create-stats-ui" to take a look, and you can grab the statisticsTable component if you want to use it. I'll leave you to finish it if you want to, since I'm pretty new to and garbage at React :stuck_out_tongue:

**Comment by ZhiHanL** [comment]
![Screenshot from 2020-05-21 22-46-55](https://user-images.githubusercontent.com/32226443/82635446-085e3900-9bb5-11ea-8da9-cc2b499c1d9c.png)

**Comment by MayKikuchi** [comment]
duplicate of #49
